### ISSUE TITLE
Add a reference to this project from the callisto-core README

### ISSUE THREAD

**Issue by kevindaum** [SexualHealthInnovations/callisto-sample-project#11]
Yeah, this should probably be an issue in callisto-core, but I don't have permission to create issues there. 

[That README](https://github.com/SexualHealthInnovations/callisto-core/blob/master/README.md) says "Want to talk about extending the code to other applications, how Callisto works, or schedule a demo of Callisto for your campus?" Once this project is in a working state, we should mention it there.

**Comment by kelseyq** [comment]
Everyone should have the ability to open issues on the callisto-core repo (green "New issue" button in the top right)--please feel free to do so as you find things in implementation!

**Comment by tpinecone** [comment]
I created the issue https://github.com/SexualHealthInnovations/callisto-core/issues/103 to replace this one
