### ISSUE TITLE
Add COORDINATOR_EMAIL to settings and document that it must be set

### ISSUE THREAD

**Issue by kevindaum** [SexualHealthInnovations/callisto-sample-project#19]
See [where it's used in callisto-core](https://github.com/SexualHealthInnovations/callisto-core/blob/master/callisto/delivery/report_delivery.py#L302). Set an example email address and add a very visible bit of documentation telling an implementer they need to change that setting or no one will receive reports.

**Comment by SaraDGore** [comment]
Submitted pull request.
